### ISSUE TITLE
run-unit-tests.yml Bug Report

### ISSUE THREAD

**Issue by PierrunoYT** [PierrunoYT/OpenDevin#21]
Here are some potential issues found in the code:

1. The `concurrency` field is not supported in the latest GitHub Actions syntax. It seems you are trying to ensure that only one run of the workflow happens at a time when pushing to the `main` branch. Instead, you can use the `if` condition in the `on.push` trigger to achieve this:

```yaml
on:
  push:
    branches:
      - main
    if: github.ref == 'refs/heads/main'
```

2. In the `test-on-macos` job, you are installing Docker using Homebrew and starting Colima. However, you are not waiting for Colima to be ready before running the tests. You can add a sleep command or check the status of Colima before proceeding with the tests:

```yaml
- name: Wait for Colima
  run: |
    until docker ps > /dev/null 2>&1; do
      echo "Waiting for Colima to be ready..."
      sleep 5
    done
```

3. In the `test-on-macos` job, the `Install & Start Docker` step sets up the Docker socket for testcontainers. However, this step is missing in the `test-on-linux` job. You should add the same step to the `test-on-linux` job to ensure testcontainers work correctly:

```yaml
- name: Set up Docker socket
  run: |
    sudo ln -sf /var/run/docker.sock /tmp/docker.sock
    export DOCKER_HOST=unix:///tmp/docker.sock
```

4. In the `test-on-linux` job, you are installing Python dependencies using `poetry install --without evaluation`. This might skip some dependencies required for testing. You should remove the `--without evaluation` flag to ensure all dependencies are installed:

```yaml
- name: Install Python dependencies using Poetry
  run: poetry install
```

5. In the `test_matrix_success` job, the `needs` keyword is used to ensure that both `test-on-macos` and `test-on-linux` jobs have completed before running this job. However, the `needs` keyword expects a list of job identifiers. You should update the `needs` field as follows:

```yaml
needs: [test-on-macos, test-on-linux]
```

After addressing these issues, your GitHub Actions workflow should work as expected.
